apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: bigdata
spec:
  serviceName: qdrant-headless
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          # Dung image da load local vao Minikube, khong pull lai tu Docker Hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-headless
  namespace: bigdata
spec:
  clusterIP: None
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
    - name: grpc
      port: 6334
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: bigdata
spec:
  type: NodePort
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      nodePort: 30333
    - name: grpc
      port: 6334
      targetPort: 6334
      nodePort: 30334
